# Generated by Django 5.1.15 on 2026-07-01 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nazwa')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#034AA4', max_length=7, verbose_name='kolor (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejnosc')),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=160, verbose_name='tytul')),
                ('body', models.TextField(blank=True, verbose_name='tresc (HTML)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
            ],
            options={
                'verbose_name': 'strona',
                'verbose_name_plural': 'strony',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nazwa')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('city', models.CharField(max_length=120, verbose_name='miejscowosc')),
                ('address', models.CharField(blank=True, max_length=220, verbose_name='adres')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='szerokosc')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='dlugosc')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='strona www')),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='instagram')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='godziny')),
                ('services', models.CharField(blank=True, max_length=300, verbose_name='uslugi (po przecinku)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='zdjecie glowne')),
                ('status', models.CharField(choices=[('pending', 'Oczekujace'), ('published', 'Opublikowane'), ('rejected', 'Odrzucone')], default='published', max_length=12, verbose_name='status')),
                ('plan', models.CharField(choices=[('free', 'Darmowy'), ('premium', 'Premium')], default='free', max_length=10, verbose_name='plan')),
                ('source', models.CharField(choices=[('admin', 'Dodane przez admina'), ('user', 'Zgloszenie uzytkownika')], default='admin', max_length=10, verbose_name='zrodlo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='directory.category', verbose_name='kategoria')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='wlasciciel')),
            ],
            options={
                'verbose_name': 'firma',
                'verbose_name_plural': 'firmy',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companies/gallery/', verbose_name='zdjecie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejnosc')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='directory.company', verbose_name='firma')),
            ],
            options={
                'verbose_name': 'zdjecie firmy',
                'verbose_name_plural': 'zdjecia firmy',
                'ordering': ['order', 'id'],
            },
        ),
    ]
